<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_59f2e69948a47',
    'title' => __('Testimonial Cards', 'modularity-testimonials'),
    'fields' => array(
        0 => array(
            'key' => 'field_59f2e6a797eff',
            'label' => __('Testimonial Cards', 'modularity-testimonials'),
            'name' => 'modularity-testimonial-cards',
            'type' => 'repeater',
            'value' => NULL,
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'collapsed' => 'field_59f2e7fdb70f6',
            'min' => 4,
            'max' => 4,
            'layout' => 'block',
            'button_label' => __('Add testimonial', 'modularity-testimonials'),
            'sub_fields' => array(
                0 => array(
                    'key' => 'field_59f2e7fdb70f6',
                    'label' => __('Image', 'modularity-testimonials'),
                    'name' => 'image',
                    'type' => 'image',
                    'value' => NULL,
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'array',
                    'preview_size' => 'thumbnail',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                ),
                1 => array(
                    'key' => 'field_59f2e6b997f00',
                    'label' => __('Name', 'modularity-testimonials'),
                    'name' => 'name',
                    'type' => 'text',
                    'value' => NULL,
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                2 => array(
                    'key' => 'field_59f2e6d997f01',
                    'label' => __('Title', 'modularity-testimonials'),
                    'name' => 'title',
                    'type' => 'text',
                    'value' => NULL,
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                3 => array(
                    'key' => 'field_59f2e6e497f02',
                    'label' => __('Testimonial', 'modularity-testimonials'),
                    'name' => 'testimonial',
                    'type' => 'textarea',
                    'value' => NULL,
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'maxlength' => '',
                    'rows' => '',
                    'new_lines' => '',
                ),
            ),
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'mod-testimonial-card',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
));
}